// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: menus.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenu = `-- name: CreateMenu :one
 INSERT INTO "menu" (
   "name",
   "description",
   "price",
   "category",
   "image",
   "restaurantId"
 ) VALUES (
   $1, $2, $3, $4, $5, $6
 ) RETURNING id, name, description, price, category, image, "restaurantId"
`

type CreateMenuParams struct {
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	Price        int32       `json:"price"`
	Category     string      `json:"category"`
	Image        string      `json:"image"`
	RestaurantId pgtype.UUID `json:"restaurantId"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.Image,
		arg.RestaurantId,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Image,
		&i.RestaurantId,
	)
	return i, err
}
