// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: restaurants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRestaurants = `-- name: CreateRestaurants :one
 INSERT INTO "restaurant" (
   "name",
   "description",
   "address",
  "logo",
  "ownerId"
 ) VALUES (
   $1, $2, $3, $4, $5
 ) RETURNING id, name, description, address, logo, "ownerId"
`

type CreateRestaurantsParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Address     string      `json:"address"`
	Logo        string      `json:"logo"`
	OwnerId     pgtype.UUID `json:"ownerId"`
}

func (q *Queries) CreateRestaurants(ctx context.Context, arg CreateRestaurantsParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, createRestaurants,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.Logo,
		arg.OwnerId,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Logo,
		&i.OwnerId,
	)
	return i, err
}
